server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 111225
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        cluster-name: HZ
#        namespace: be01e8ef-f8de-428c-95a6-33aaeb2830d6 # 命名空间id


mybatis:
  type-aliases-package: com.xn2001.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.xn2001: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#feign日志设置
#feign:
#  client:
#    config:
#      userservice:  # 针对某个微服务的配置
#        loggerLevel: FULL # 日志级别
#feign开启httpClient的支持
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50